site_name: OuterSpace Apizr
site_url: https://apizr.outerspace.sh
site_author: Ludovic FERNANDEZ, Alien6
site_description: >-
  OuterSpace Apizr

# Repository
repo_name: alien6-studio/outerspace-apizr
repo_url: https://github.com/alien6-studio/outerspace-apizr

# Copyright
copyright: Copyright &copy; 2023 Alien6

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.png
  icon:
    repo: fontawesome/brands/github-alt 
  palette:
    - scheme: default
      primary: amber
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: amber
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
    favicon: assets/images/logo.png
  features:
    - announce.dismiss
    - announce.hide
    # - content.action.edit
    # - content.action.view
    # - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    #- toc.integrate
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html

extra:
  generator: false
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
  analytics:
    provider: google
    property: G-P3BHZB2FVP

extra_css:
  - assets/stylesheets/extra.css

# Page tree
nav:
  - Home: index.md
  - Getting Started:
    - Introduction: getting-started/introduction.md
    - Modules:
      - Notebook Transformr: modules/notebook-transformr.md
      - Code Analyzr: modules/code-analyzr.md
      - Fast Apizr: modules/fast-apizr.md
      - Dockerizr: modules/dockerizr.md
    - APIs:
      - Notebook Transformr API: apis/notebook-transformr-api.md
      - Code Analyzr API: apis/code-analyzr-api.md
      - Fast Apizr API: apis/fast-apizr-api.md
      - Dockerizr API: apis/dockerizr-api.md
    - About:
      - Contributing: about/CONTRIBUTING.md
      - Code of Conduct: about/CODE_OF_CONDUCT.md
      - License: about/LICENSE.md
