"""Preparation rejects unsupported resolver syntax and incomplete artifact evidence."""

import json
import shutil
import sys
from pathlib import Path
from threading import Event

import pytest

from apizr.cli import main
from apizr.plugins.preparation import requirements, selection
from apizr.plugins.preparation.models import (
    AdmittedPin,
    PreparationError,
    PreparationResult,
)
from apizr.plugins.preparation.operations import prepare_plugin
from apizr.plugins.preparation.requirements import parse_resolver_lock

HASH = "a" * 64
LINE = f"example==1.0 --hash=sha256:{HASH}\n"


@pytest.mark.parametrize(
    "line",
    [
        "",
        "# nothing\n",
        "example>=1.0",
        "example==1.*",
        "-e example",
        "-r other.lock",
        "-c constraint",
        "./local.whl",
        "https://example.test/pkg.whl",
        "example @ https://example.test/pkg.whl",
        f"example==1.0; python_version > '3.11' --hash=sha256:{HASH}",
        f"example[extra]==1.0 --hash=sha256:{HASH}",
        f"example==1.0 --hash=md5:{HASH}",
        f"example==1.0 --hash=sha256:{HASH} --unknown",
        "example==1.0 --hash=sha256:abc",
        f"example==1.0 --hash=sha256:{HASH}#hidden",
        LINE + LINE,
        LINE + f"EXAMPLE==1.0 --hash=sha256:{HASH}\n",
        b"\xff",
    ],
)
def test_resolver_subset_is_not_a_general_requirements_parser(line):
    with pytest.raises(PreparationError, match="invalid_resolver_lock"):
        parse_resolver_lock(line if isinstance(line, bytes) else line.encode())


def test_comments_hash_sets_and_names_are_canonical():
    raw = (
        f"# generated by uv\nSome_Package==1.0 \\\n  --hash=sha256:{'B' * 64} \\\n  --hash=sha256:{HASH}  # via plugin\n"
    ).encode()
    assert parse_resolver_lock(raw) == (
        AdmittedPin(name="some-package", version="1.0", hashes=(HASH, "b" * 64)),
    )


@pytest.mark.parametrize(
    "constant,value,raw,reason",
    [
        ("MAX_REQUIREMENTS_BYTES", 1, LINE, "resolver_lock_too_large"),
        (
            "MAX_HASHES",
            1,
            LINE.rstrip() + f" --hash=sha256:{'b' * 64}\n",
            "invalid_resolver_lock",
        ),
        (
            "MAX_WHEELS",
            1,
            LINE + LINE.replace("example", "second"),
            "invalid_resolver_lock",
        ),
    ],
)
def test_resolver_input_bounds(monkeypatch, constant, value, raw, reason):
    monkeypatch.setattr(requirements, constant, value)
    with pytest.raises(PreparationError, match=reason):
        parse_resolver_lock(raw.encode())


def test_new_result_requires_a_complete_preparation_or_an_explicit_refusal():
    for state in ("prepared", "refused", "interrupted"):
        with pytest.raises(ValueError):
            PreparationResult(state=state)
    with pytest.raises(ValueError):
        PreparationResult.model_validate({"state": "refused", "unexpected": True})


def test_installer_multihash_error_explains_preparation_without_installing(
    chain, tmp_path, capsys
):
    plugin, digest, lock, house = chain
    raw = lock.read_text().replace(
        f"--hash=sha256:{digest}", f"--hash=sha256:{'0' * 64} --hash=sha256:{digest}"
    )
    lock.write_text(raw)
    profile = tmp_path / "profile"
    assert (
        main(
            [
                "plugins",
                "install",
                str(plugin),
                "--sha256",
                digest,
                "--requirements",
                str(lock),
                "--wheelhouse",
                str(house),
                "--plugins-dir",
                str(profile),
            ]
        )
        == 2
    )
    output = capsys.readouterr()
    diagnostic = json.loads(output.err.splitlines()[0])
    assert diagnostic["reason"] == "multiple_hashes_require_preparation"
    assert diagnostic["distribution"] == "local-probe"
    assert diagnostic["suggested_operation"] == "prepare"
    assert "invalid_requirements_lock" in output.err and not profile.exists()


@pytest.mark.parametrize(
    "case,reason",
    [
        ("parent_symlink", "preparation_io_refused"),
        ("house_symlink", "preparation_io_refused"),
        ("wheel_symlink", "regular_wheel_required"),
        ("existing_dir", "output_exists"),
        ("existing_file", "output_exists"),
        ("existing_symlink", "output_exists"),
        ("missing_interpreter", "interpreter_unavailable"),
        ("relative_interpreter", "interpreter_unavailable"),
        ("foreign_platform", "target_invalid"),
        ("invalid_lock", "invalid_resolver_lock"),
        ("cancelled", "preparation_cancelled"),
        ("corrupt_wheel", "invalid_wheel"),
    ],
)
def test_explicit_boundaries_refuse_and_remove_staging(chain, tmp_path, case, reason):
    plugin, _, lock, house = chain
    shutil.copyfile(plugin, house / plugin.name)
    output = tmp_path / "prepared"
    python, platform, cancel = Path(sys.executable), "native", None
    if case == "parent_symlink":
        link = tmp_path / "parent-link"
        link.symlink_to(tmp_path, target_is_directory=True)
        output = link / "prepared"
    elif case == "house_symlink":
        link = tmp_path / "house-link"
        link.symlink_to(house, target_is_directory=True)
        house = link
    elif case == "wheel_symlink":
        (house / plugin.name).unlink()
        (house / plugin.name).symlink_to(plugin)
    elif case == "existing_dir":
        output.mkdir()
    elif case == "existing_file":
        output.write_text("preserve me")
    elif case == "existing_symlink":
        output.symlink_to(tmp_path / "missing")
    elif case == "missing_interpreter":
        python = tmp_path / "absent-python"
    elif case == "relative_interpreter":
        python = Path("python")
    elif case == "foreign_platform":
        platform = "win_amd64"
    elif case == "invalid_lock":
        lock.write_text("--extra-index-url https://secret.invalid\n")
    elif case == "cancelled":
        cancel = Event()
        cancel.set()
    elif case == "corrupt_wheel":
        (house / plugin.name).write_bytes(b"not a zip")
    result = prepare_plugin(
        "local-probe",
        "1.0",
        python=python,
        platform=platform,
        output_dir=output,
        wheelhouse=house,
        requirements=lock,
        cancel=cancel,
    )
    assert result.diagnostics[0].reason == reason, result
    assert result.exit_code == (130 if case == "cancelled" else 2)
    if not case.startswith("existing"):
        assert not output.exists()
    assert not list(tmp_path.glob(".apizr-preparation-*"))
    assert str(tmp_path) not in result.model_dump_json()


@pytest.mark.parametrize(
    "raw",
    [
        b"not toml",
        b'lock-version="2.0"',
        b'lock-version="1.0"\ncreated-by="uv"\npackages=[1]',
        b'lock-version="1.0"\ncreated-by="uv"\npackages=[]',
    ],
)
def test_malformed_machine_resolver_output_is_refused(raw):
    with pytest.raises(PreparationError, match="invalid_resolver_artifacts"):
        selection.resolver_candidates(raw, parse_resolver_lock(LINE.encode()), None)
