# Use an Ubuntu-based Python image
FROM python:{{ python_version }}-{{ docker_image_tag }}

# Update packages and install necessary dependencies
RUN apt-get update && apt-get install -y curl

# Create a non-privileged user
RUN groupadd outerspacer && useradd -m -g outerspacer -s /bin/sh outerspacer

# Set environment variables
ENV PYTHONPATH /app:$PYTHONPATH

# Copy the source code into the container
COPY . /app

# Copy the start script into the container
COPY start.sh /app/start.sh
RUN chmod +x /app/start.sh

# Copy the entrypoint script into the container
{% if entrypoint %}
RUN echo {{ entrypoint }} >> /app/entrypoint.sh && \
    chmod +x /entrypoint.sh
{% endif %}

# Set the working directory
WORKDIR /app

# Install dependencies
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# Remove unnecessary dependencies and cleanup
RUN apt-get remove -y gcc \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Change ownership for the application directory
RUN chown -R outerspacer:outerspacer /app

# Use the new user to run the container
USER outerspacer

# Expose the service
EXPOSE {{ port }}

# Add a health check
HEALTHCHECK --interval=5m --timeout=3s \
  CMD curl -f http://localhost:{{ port }}/docs || exit 1

# Run the application
ENTRYPOINT ["/app/start.sh"]
